apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenops-dashboard
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenops-dashboard
  template:
    metadata:
      labels:
        app: greenops-dashboard
    spec:
      containers:
        - name: dashboard
          image: gcr.io/PROJECT_ID/greenops-dashboard:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greenops-dashboard
  namespace: boutique
spec:
  type: LoadBalancer
  selector:
    app: greenops-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
