apiVersion: v1
kind: ServiceAccount
metadata:
  name: greenops-selfheal
  namespace: boutique
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greenops-selfheal-role
  namespace: boutique
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greenops-selfheal-binding
  namespace: boutique
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: greenops-selfheal-role
subjects:
  - kind: ServiceAccount
    name: greenops-selfheal
    namespace: boutique
